/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Roshana Perera
 */
public class SupplierManagementUI extends javax.swing.JFrame {
    
    public static String filenameGlo;
    public static String GloVehicleNo;
    public static String GloSupplierNo;
    /**
     * Creates new form SupplierManagementUI
     */
    public SupplierManagementUI() {
        initComponents();
        table_update();
        txtPDate.setDateFormatString("yyyy-MM-dd");
        txtRDate.setDateFormatString("yyyy-MM-dd");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtContactno = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPDate = new com.toedter.calendar.JDateChooser();
        txtRDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtVehicleNo = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtMileage = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehicle = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(25, 35, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier Management");

        jPanel2.setBackground(new java.awt.Color(71, 120, 217));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Vehicle No.");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier Information");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setNextFocusableComponent(txtAddress);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pickup Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Return Date");

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAddress.setNextFocusableComponent(txtNIC);

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNIC.setNextFocusableComponent(txtContactno);

        txtContactno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContactno.setNextFocusableComponent(txtEmail);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setNextFocusableComponent(txtPDate);

        txtPDate.setNextFocusableComponent(txtRDate);

        txtRDate.setNextFocusableComponent(txtMake);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vehicle Information");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Make");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Model");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Vehicle No.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Year");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mileage");

        txtMake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMake.setNextFocusableComponent(txtModel);

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtModel.setNextFocusableComponent(txtVehicleNo);

        txtVehicleNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVehicleNo.setNextFocusableComponent(txtYear);
        txtVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNoActionPerformed(evt);
            }
        });

        txtYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtYear.setNextFocusableComponent(txtMileage);

        txtMileage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMileage.setNextFocusableComponent(txtRate);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Rate");

        txtRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRate.setNextFocusableComponent(txtDescription);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setNextFocusableComponent(btnSubmit);
        jScrollPane1.setViewportView(txtDescription);

        btnSubmit.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        btnSubmit.setText("Submit Details");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon("D:\\Roshana Perera\\Documents\\NetBeansProjects\\EUROCarRentalSystem\\images\\car.jpg")); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnImage.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        btnImage.setText("Browse Image");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        btnUpdate.setText("Update Details");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblVehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle No.", "Make", "Model", "Supplier Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehicleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVehicle);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNIC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContactno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(txtRDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addGap(80, 80, 80))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel17))
                                    .addGap(103, 103, 103)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel12)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnImage)
                                .addGap(128, 128, 128))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 35, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtPDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtRDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnImage)
                                .addGap(18, 18, 18)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnClear)
                            .addComponent(btnUpdate))))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(531, 531, 531))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblVehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehicleMouseClicked
        // TODO add your handling code here:
        Connection conn;
        PreparedStatement ps,ps1;
        ResultSet rs,rs1;
        try
        {
            int row = tblVehicle.getSelectedRow();
            String TableClick=(tblVehicle.getModel().getValueAt(row,0).toString());
            String sql = ("SELECT * FROM vehicle v INNER JOIN supplier s on v.vehicleNo = s.vehicleNo WHERE v.vehicleNo = '"+TableClick+"'");
            //String sql = ("select * from vehicle where vehicleNo = '"+TableClick+"'");
            //String sq2 = ("select * from supplier where vehicleNo = '"+TableClick+"'");
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
            ps = conn.prepareStatement(sql);
            //ps1 = conn.prepareStatement(sq2);
            rs = ps.executeQuery();
            //rs1 = ps1.executeQuery();

            if (rs.next())
            {
                //GloVehicleNo = rs.getString("vehicleNo");
                txtVehicleNo.setText(rs.getString("vehicleNo"));
                txtMake.setText(rs.getString("make"));
                txtModel.setText(rs.getString("model"));
                txtMileage.setText(rs.getString("mileage"));
                txtYear.setText(rs.getString("year"));
                txtDescription.setText(rs.getString("description"));
                txtPDate.setDate(rs.getDate("pickupDate"));
                txtRDate.setDate(rs.getDate("returnDate"));
                txtRate.setText(rs.getString("rate"));
                String tempPath = (rs.getString("imagePath"));
                //GloSupplierNo = (rs1.getString("supplierID"));
                txtName.setText(rs.getString("supplierName"));
                txtAddress.setText(rs.getString("supplierAddress"));
                txtNIC.setText(rs.getString("supplierNIC"));
                txtContactno.setText(rs.getString("supplierContactNO"));
                txtEmail.setText(rs.getString("supplierEmail"));
                
                ImageIcon imageicon = new ImageIcon(new ImageIcon(tempPath).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
                lblImage.setIcon(imageicon);
                
                //JOptionPane.showMessageDialog(null, GloSupplierNo);
                //JOptionPane.showMessageDialog(null, GloVehicleNo);
                //txtPDate.setDate(v7);
                //String v8 =rs.getString("returnDate");
                //txtRDate.setDate(v8);
                //String v10 =rs.getString("imagePath");
                //txt.setText(v10);
                
                conn.close();
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblVehicleMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String suppliername = txtName.getText();
        String supplieraddress = txtAddress.getText();
        String supplierNIC = txtNIC.getText();
        String suppliercontactno = txtContactno.getText();
        String supplieremail = txtEmail.getText();
        String vehicleno = txtVehicleNo.getText();
        String make = txtMake.getText();
        String model = txtModel.getText();
        String mileage = txtMileage.getText();
        String year = txtYear.getText();
        String description = txtDescription.getText();
        SimpleDateFormat dateformat1 = new SimpleDateFormat("yyyy-MM-dd");
        String pdate = dateformat1.format(txtPDate.getDate());
        SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
        String rdate = dateformat2.format(txtRDate.getDate());
        int rate = Integer.parseInt(txtRate.getText());

        Connection conn;
        PreparedStatement ps;
        PreparedStatement pst;
        
        boolean ans=validatesupplierform(suppliername,supplieraddress,supplierNIC,suppliercontactno,supplieremail,pdate ,rdate);
        boolean ans2=validatevehicleform(vehicleno,make,model,year,mileage,description,rate);
        if(ans==false && ans2==false)
        {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
            String sql = ("INSERT INTO `vehicle` (`vehicleID`, `vehicleNo`, `make`, `model`, `mileage`, `year`, `description`, `pickupDate`, `returnDate`, `rate`, `imagePath`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            String sq2 = ("INSERT INTO `supplier` (`supplierID`, `supplierName`, `supplierAddress`, `supplierNIC`, `supplierContactNo`, `supplierEmail`, `vehicleNo`) VALUES (NULL,?,?,?,?,?,?)");
            ps = conn.prepareStatement(sql);
            ps.setString(1, vehicleno);
            ps.setString(2, make);
            ps.setString(3, model);
            ps.setString(4, mileage);
            ps.setString(5, year);
            ps.setString(6, description);
            ps.setString(7, pdate);
            ps.setString(8, rdate);
            ps.setInt(9, rate);
            ps.setString(10, filenameGlo);
            pst = conn.prepareStatement(sq2);
            pst.setString(1, suppliername);
            pst.setString(2, supplieraddress);
            pst.setString(3, supplierNIC);
            pst.setString(4, suppliercontactno);
            pst.setString(5, supplieremail);
            pst.setString(6, vehicleno);

            ps.executeUpdate();
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Vehicle Added Successfully !");
            table_update();

            txtVehicleNo.setText("");
            txtMake.setText("");
            txtModel.setText("");
            txtMileage.setText("");
            txtYear.setText("");
            txtDescription.setText("");
            txtPDate.setDate(null);
            txtRDate.setDate(null);
            txtRate.setText("");
            txtName.setText("");
            txtAddress.setText("");
            txtNIC.setText("");
            txtContactno.setText("");
            txtEmail.setText("");

            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNoActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
            String searchq = txtSearch.getText();
            if(searchq==null || searchq.equals("")||!searchq.matches("^[A-Za-z]+[-][0-9]{4}+$")||!(searchq.length()<10))
            {
                JOptionPane.showMessageDialog(null, "Please enter valid vehicle-no.");
            }
            String sql1 = ("select * from vehicle where vehicleNo = '"+searchq+"'");
            String sql2 = ("select * from supplier where vehicleNo = '"+searchq+"'");
            PreparedStatement pst1 = con.prepareStatement(sql1);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            ResultSet rs1 = pst1.executeQuery();
            ResultSet rs2 = pst2.executeQuery();
            
            if (rs1.next()&& rs2.next())
            {
                txtVehicleNo.setText(rs1.getString("vehicleNo"));
                txtMake.setText(rs1.getString("make"));
                txtModel.setText(rs1.getString("model"));
                txtMileage.setText(rs1.getString("mileage"));
                txtYear.setText(rs1.getString("year"));
                txtDescription.setText(rs1.getString("description"));
                txtPDate.setDate(rs1.getDate("pickupDate"));
                txtRDate.setDate(rs1.getDate("returnDate"));
                txtRate.setText(rs1.getString("rate"));
                String tempPath = (rs1.getString("imagePath"));
                txtName.setText(rs2.getString("supplierName"));
                txtAddress.setText(rs2.getString("supplierAddress"));
                txtNIC.setText(rs2.getString("supplierNIC"));
                txtContactno.setText(rs2.getString("supplierContactNO"));
                txtEmail.setText(rs2.getString("supplierEmail"));
                
                ImageIcon imageicon = new ImageIcon(new ImageIcon(tempPath).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
                lblImage.setIcon(imageicon);
            }
            
            con.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        String filename = null;
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
        filenameGlo = filename;
        //JOptionPane.showMessageDialog(null, filenameGlo);
        lblImage.setIcon(imageicon);
//        try
//        {
//            
//        }
//        catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            txtVehicleNo.setText("");
            txtMake.setText("");
            txtModel.setText("");
            txtMileage.setText("");
            txtYear.setText("");
            txtDescription.setText("");
            txtPDate.setDate(null);
            txtRDate.setDate(null);
            txtRate.setText("");
            txtName.setText("");
            txtAddress.setText("");
            txtNIC.setText("");
            txtContactno.setText("");
            txtEmail.setText("");
            String tempPath =null;
            ImageIcon imageicon = new ImageIcon(new ImageIcon(tempPath).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
            lblImage.setIcon(imageicon);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String mileage = txtMileage.getText();
        String description = txtDescription.getText();
        SimpleDateFormat dateformat1 = new SimpleDateFormat("yyyy-MM-dd");
        String pdate = dateformat1.format(txtPDate.getDate());
        SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
        String rdate = dateformat2.format(txtRDate.getDate());
        int rate = Integer.parseInt(txtRate.getText());
        String contactNo=txtContactno.getText();
        String email=txtEmail.getText();
        String address=txtAddress.getText();
        String name = txtName.getText();
        
        boolean ans=updatesupplier(contactNo,email,pdate,rdate,mileage,description,rate,address);
        if(ans==false)
        {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
            Statement st = con.createStatement();
            String sql = "UPDATE `vehicle` SET `mileage`='"+mileage+"',`description`='"+description+"',`pickupDate`='"+pdate+"',`returnDate`='"+rdate+"',`rate`='"+rate+"' WHERE vehicleNo = '" +txtVehicleNo.getText()+ "'";
            st.executeUpdate(sql);
            String sq2 = "UPDATE `supplier` SET `supplierName`='"+name+"',`supplierAddress`='"+address+"',`supplierContactNo`='"+contactNo+"',`supplierEmail`='"+email+"' WHERE vehicleNo = '" +txtVehicleNo.getText()+ "'";
            st.executeUpdate(sq2);
            table_update();
            JOptionPane.showMessageDialog(this, ""+txtVehicleNo.getText()+ " is Updated ! ");
            con.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        //String suppliername = txtName.getText();
        //String supplieraddress = txtAddress.getText();
        //String supplierNIC = txtNIC.getText();
        //String suppliercontactno = txtContactno.getText();
        //String supplieremail = txtEmail.getText();
//        String vehicleno = txtVehicleNo.getText();
//        String make = txtMake.getText();
//        String model = txtModel.getText();
//        String mileage = txtMileage.getText();
//        String year = txtYear.getText();
//        String description = txtDescription.getText();
//        SimpleDateFormat dateformat1 = new SimpleDateFormat("yyyy-MM-dd");
//        String pdate = dateformat1.format(txtPDate.getDate());
//        SimpleDateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
//        String rdate = dateformat2.format(txtRDate.getDate());
//        int rate = Integer.parseInt(txtRate.getText());
//
//        try
//        {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
//            Statement st = con.createStatement();
//            //JOptionPane.showMessageDialog(null, GloVehicleNo);
//            String sql = "UPDATE vehicle SET `make` = '"+make+"' WHERE vehicleNo = '" +txtVehicleNo.getText()+ "'";
//            
//            st.executeUpdate(sql);
//            table_update();
//            
//            con.close();
//        }
//        catch (Exception e)
//        {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void table_update()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3308/euro_db", "root", "");
            PreparedStatement pst = con.prepareStatement("SELECT * FROM vehicle v INNER JOIN supplier s on v.vehicleNo = s.vehicleNo");
            //PreparedStatement pst2 = con.prepareStatement("SELECT * FROM supplier");
            ResultSet rs = pst.executeQuery();
            //ResultSet rs2 = pst2.executeQuery();
            ResultSetMetaData rd  = rs.getMetaData();
            //ResultSetMetaData rd2  = rs2.getMetaData();
            int c = rd.getColumnCount();
            //int c2 = rd2.getColumnCount();
            DefaultTableModel df  = (DefaultTableModel)tblVehicle.getModel();
            
            df.setRowCount(0);
            
            while (rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("vehicleNo"));
                    v2.add(rs.getString("make"));
                    v2.add(rs.getString("model"));
                    v2.add(rs.getString("supplierName"));
                }
                df.addRow(v2);
            }

            con.close();
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierManagementUI().setVisible(true);
            }
        });
    }
    
    public boolean validatesupplierform(String name,String address,String NIC,String contactno,String email,String Pdate,String rdate)
    {
        boolean errorFlag = false;

        DateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
        String dateString2 = dateFormat2.format(new Date());
        if(name==null || name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-name.");
            errorFlag=true;
        }
        if(address==null || address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-address.");
            errorFlag=true;
        }
        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcher = pattern.matcher(contactno);
        
        if(contactno==null || contactno.equals("")||! matcher.matches())
        {
            
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-contact number");
            errorFlag=true;
        }
        
        if(email==null || email.equals("")||!email.matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-email address.");
            errorFlag=true;
        }

        if(NIC==null || NIC.equals("")||!NIC.matches("^[0-9]{0,12}[vVxX]$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-NIC.");
            errorFlag=true;
        }
        
        if (!(Pdate.equals(dateString2)))
        {
            JOptionPane.showMessageDialog(null, "Pick up date shold be todays day.");
            errorFlag=true;
        }
        if(!(Pdate.compareTo(rdate)<0))
        {
            JOptionPane.showMessageDialog(null, "Return Date should be further date than pickup date.");
            errorFlag=true;
        }
        return errorFlag;
         
    }
    //,String model,String year,String mileage,String desc,int rate
    public boolean validatevehicleform(String vehicleno,String make,String model,String year,String mileage,String desc,int rate)
    {
        boolean errorFlag = false;
        if(vehicleno==null || vehicleno.equals("")||!vehicleno.matches("^[A-Za-z]+[-][0-9]{4}+$")||!(vehicleno.length()<10))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-no.");
            errorFlag=true;
        }
        if(make==null || make.equals("")||!make.matches("^[A-Za-z]{0,9}+$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-make.");
            errorFlag=true;
        }
        if(model==null || model.equals("")||!model.matches("^[A-Za-z0-9]{0,9}$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-module.");
            errorFlag=true;
        }
        if(year==null || year.equals("")|| !year.matches("[0-9]{0,4}")) 
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-manufacture year.");
            errorFlag=true;
        }
        
        if(mileage==null || mileage.equals("")|| !mileage.matches("[0-9]{0,6}"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-mileage.");
            errorFlag=true;
        }
        if(desc==null || desc.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter vehicle -description.");
            errorFlag=true;
        }
        
        String text= String.valueOf(rate);
        Pattern pattern2 = Pattern.compile("\\d{0,5}");
        Matcher matcher2 = pattern2.matcher(text);
        if(text==null || !matcher2.matches())
        {
            JOptionPane.showMessageDialog(null, "Please enter vehicle -cost.");
            errorFlag=true;
        }
         return errorFlag;
    }
    
    public boolean updatesupplier(String contactno,String email,String Pdate,String rdate,String mileage,String desc,int rate,String address)
    {
        boolean errorFlag=false;
        Pattern pattern = Pattern.compile("\\d{10}");
        Matcher matcher = pattern.matcher(contactno);
        
        if(contactno==null || contactno.equals("")||! matcher.matches())
        {
            
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-contact number");
            errorFlag=true;
        }
        if(email==null || email.equals("")||!email.matches("^[A-Za-z0-9_.]+[@][A-Za-z.]+$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-email address.");
            errorFlag=true;
        }
        DateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd");
        String dateString2 = dateFormat2.format(new Date());
        
        if(address==null || address.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid supplier-address.");
            errorFlag=true;
        }
         if (!(Pdate.equals(dateString2)))
        {
            JOptionPane.showMessageDialog(null, "Pick up date shold be todays day.");
            errorFlag=true;
        }
        if(!(Pdate.compareTo(rdate)<0))
        {
            JOptionPane.showMessageDialog(null, "Return Date should be further date than pickup date.");
            errorFlag=true;
        }
        if(desc==null || desc.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter vehicle -description.");
            errorFlag=true;
        }
        if(mileage==null || mileage.equals("")|| !mileage.matches("[0-9]{0,6}"))
        {
            JOptionPane.showMessageDialog(null, "Please enter valid vehicle-mileage.");
            errorFlag=true;
        }
        String text= String.valueOf(rate);
        Pattern pattern2 = Pattern.compile("\\d{0,5}");
        Matcher matcher2 = pattern2.matcher(text);
        if(mileage==null || !matcher2.matches())
        {
            JOptionPane.showMessageDialog(null, "Please enter vehicle -cost.");
            errorFlag=true;
        }
        return errorFlag;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblVehicle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactno;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private com.toedter.calendar.JDateChooser txtPDate;
    private com.toedter.calendar.JDateChooser txtRDate;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtVehicleNo;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
